# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu
---
- name: generate check_mk local ping checks
  ansible.builtin.template:
    src: check_ping.j2
    dest: "/usr/lib/check_mk_agent/local/check_ping_{{ item.key }}"
    mode: 0755
  with_dict: "{{ local_ping_checks }}"
...
