---
name: ansible-lint
on:
  pull_request:
  push:
  schedule:
    - cron: "30 5 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run ansible-lint
        uses: ansible/ansible-lint-action@v6.18.0
        with:
          path: '.'
